### ISSUE TITLE
Compatibility with The Fox Only Better's Slim Chrome feature

### ISSUE THREAD

**Issue by Quicksaver** [louischan/simplewhite#37]
Hi, I'm the developer of the add-on [The Fox, Only Better](https://addons.mozilla.org/firefox/addon/the-fox-only-better/). A user reported a problem (https://github.com/Quicksaver/The-Fox--Only-Better/issues/100) when using it together with this theme. I wonder if you could add support for the add-on within the theme, as this task will be much more easily done within the theme itself.

You can check out and follow https://github.com/Quicksaver/The-Fox--Only-Better/issues/24 for simple instructions on how to add support for the add-on in themes, and of course if you have any questions or need me to do anything in the add-on for this, please let me know. :)

**Comment by louischan** [comment]
The patch is not perfect, but it should look better than before. :)

**Comment by Quicksaver** [comment]
Looks great! Is there any chance you could add the following code to make the edges of the toolbar stay inside the limits?

```CSS
#main-window:not([chromehidden~="toolbar"]) #navigator-toolbox[slimStyle="australis"] #theFoxOnlyBetter-slimChrome-container:-moz-any([hover],:not([onlyURLBar])) #nav-bar {
  margin-left: 0;
  margin-right: 0;
}
```
